baseURL = 'https://roojery.com/'
languageCode = 'en-us'
title = 'Brian Ruggieri'
theme = 'resume'
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "vim"
enableGitInfo = false

[params]
address = "Athens, GA"
email = "brianruggieri@gmail.com"
favicon = "/favicon.ico"
firstName = "Brian"
lastName = "Ruggieri"
backgroundMode = "canvas"
phone = "REDACTED"
profileImage = "img/jake.jpg"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = true
sections = ["skills","creations","experience","education"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/roojerry/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/brianruggieri/"

[[params.handles]]
    name = "Instagram"
    link = "https://www.instagram.com/roojerry/"
    icon = "instagram"

[[params.handles]]
    name = "Facebook"
    link = "https://www.facebook.com/josephbrianruggieri/"
    icon = "facebook"

# [[params.handles]]
#     link = "https://stackoverflow.com/users/82880/eddie"
#     name = "Stack Overflow"
#     icon = "stack-overflow"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true
